# Generated by Django 5.0.7 on 2024-08-04 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_managers_remove_user_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_employee',
            new_name='is_agent',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_customer',
            new_name='is_manager',
        ),
    ]
